name: homework 22

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd ./hw-22-probabilistic-algorithm
          go mod download
          go test -v ./...
